### ISSUE TITLE
Python script misses shebang line.

### ISSUE THREAD

**Issue by dreirund** [Zerocopter/J2J#1]
Ahoj,

I am creating [&nearr;&hairsp;an Arch Linux package](https://aur.archlinux.org/packages/j2j-git) from this.

In the [`README.md`](https://github.com/Zerocopter/J2J/blob/main/README.md) you write for usage information

```
Usuage: J2J.py <filename>
```

But for this to work `J2J.py` misses a proper [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) line, so that the operating system knows that it has to use the python interpreter for the file. (By default, if executed from the shell, it would treat the script as a shell script and not as a python script.)

Please add a proper shebang line (e.g. `#!/usr/bin/env python3`) as first line of the script.

Regards!

**Comment by Staatsgeheim** [comment]
Ahoj!

That awesome! 
I've fixed the shebang line!

Thanks for your report!

Kind regards
Maarten Boone
